import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sonner';
import { Navigation } from '@/components/shared/Navigation';
import { LoadingProvider } from '@/contexts/LoadingContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// TODO: 認証、認可管理
// async function getAuthUser() {
//   const res = await fetch(`${process.env.API_BASE_URL}/articles`, {
//     method: 'GET',
//     headers: {
//       'Content-Type': 'application/json',
//       Accept: 'application/json',
//     },
//   });
//   // if(!res.ok) redirect /login

//   return res.json();
// }

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const authUser = await getAuthUser();
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex flex-col items-center mt-2 gap-4">
          <LoadingProvider>
            {/* <AuthProvider authUser> */}
            <Navigation /* authUser={authUser}*/ />
            {children}
            {/* </AuthProvider> */}
          </LoadingProvider>
        </div>
        <Toaster richColors position="top-center" duration={5000} />
      </body>
    </html>
  );
}
