import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sonner';
import { Navigation } from '@/components/shared/navigatoin/Navigation';
import { LoadingProvider } from '@/contexts/LoadingContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex flex-col items-center mt-2 gap-4 w-[900px] mx-auto">
          <LoadingProvider>
            <Navigation />
            {children}
          </LoadingProvider>
        </div>
        <Toaster richColors position="top-center" duration={5000} />
      </body>
    </html>
  );
}
