services:

  # Appサーバ（PHP+Laravel）
  ref-app-server:
    build: ./docker-config/php
    container_name: ref-app-server
    ports:
      - '8001:8000'
    volumes:
      - ./src_ref:/var/www/html
      - ./docker-config/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
